name: Push to Master
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Update NDP Submodule
    runs-on: ubuntu-latest
    steps:
    - name: Update NDP Submodule
      uses: nexmo/github-actions/submodule-auto-pr@master
      env:
        GH_ADMIN_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
        PR_ACTIVE_BRANCH: master
        PR_BRANCH_NAME: automated-php-snippets-update
        PR_SUBMODULE_PATH: .repos/nexmo/nexmo-php-code-snippets
        PR_TARGET_BRANCH: master
        PR_TARGET_ORG: nexmo
        PR_TARGET_REPO: nexmo-developer
        PR_TITLE: nexmo-php-code-snippets Update
